---

include:
  - project: veepee/vptech/sre/iac/ci-cd/docker-lint
    ref: 2.0.0
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/docker-build
    ref: 4.2.2
    file: gitlab-ci-build.yml
  - project: veepee/vptech/sre/iac/ci-cd/markdown-lint
    ref: 1.2.0
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/semantic-release
    ref: 2.9.0
    file: gitlab-ci.yml

variables:
  APP_NAME: ansible
  DOCKER_DISABLE_ALL_JOBS: 'true'
  DOCKER_PUBLIC_REGISTRY_URL: docker.io
  DOCKER_PUBLIC_REGISTRY_USERNAME: ${PUBLIC_REGISTRY_USERNAME}
  DOCKER_PUBLIC_REGISTRY_PASSWORD: ${PUBLIC_REGISTRY_PASSWORD}
  DOCKER_PUBLIC_REPO: vptech
  PUBLIC: 'true'
  SEMANTIC_CONFIG_FILE: changelog

stages:
  - lint
  - build
  - test
  - publish
  - release

public:v2.7:
  extends: .publish-public:docker
  variables:
    DOCKER_BUILD_ARGS: --build-arg ANSIBLE_VERSION=2.7.13
    TAG: 2.7.13 2.7

public:v2.8:
  extends: .publish-public:docker
  variables:
    DOCKER_BUILD_ARGS: --build-arg ANSIBLE_VERSION=2.8.6
    TAG: 2.8.6 2.8

public:v2.9:
  extends: .publish-public:docker
  variables:
    DOCKER_BUILD_ARGS: --build-arg ANSIBLE_VERSION=2.9.10
    TAG: 2.9.11 2.9 latest
...
